export const CAT_BREEDS: string[] = [
  'Abyssinian',
  'American Shorthair',
  'Bengal',
  'Birman',
  'British Shorthair',
  'Burmese',
  'Devon Rex',
  'Domestic Longhair',
  'Domestic Shorthair',
  'Exotic Shorthair',
  'Himalayan',
  'Maine Coon',
  'Manx',
  'Norwegian Forest Cat',
  'Oriental Shorthair',
  'Persian',
  'RagaMuffin',
  'Ragdoll',
  'Russian Blue',
  'Scottish Fold',
  'Siamese',
  'Somali',
  'Sphynx',
  'Tonkinese',
  'Turkish Angora',
  'Mixed Breed',
  'Other',
]

export const BREEDS: string[] = [
  'Akita',
  'American Pit Bull Terrier / Pit Bull Mix',
  'Australian Cattle Dog',
  'Australian Shepherd',
  'Basset Hound',
  'Beagle',
  'Belgian Malinois',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Border Collie',
  'Boston Terrier',
  'Boxer',
  'Cane Corso',
  'Cavalier King Charles Spaniel',
  'Chihuahua',
  'Cocker Spaniel',
  'Dachshund',
  'Dalmatian',
  'Doberman Pinscher',
  'English Bulldog',
  'English Mastiff',
  'English Springer Spaniel',
  'French Bulldog',
  'German Shepherd',
  'German Shorthaired Pointer',
  'Golden Retriever',
  'Goldendoodle',
  'Great Dane',
  'Great Pyrenees',
  'Havanese',
  'Irish Setter',
  'Jack Russell Terrier',
  'Labradoodle',
  'Labrador Retriever',
  'Maltese',
  'Maremma Sheepdog',
  'Miniature Poodle',
  'Miniature Schnauzer',
  'Pembroke Welsh Corgi',
  'Pomeranian',
  'Rottweiler',
  'Shetland Sheepdog (Sheltie)',
  'Shih Tzu',
  'Siberian Husky',
  'Staffordshire Bull Terrier',
  'Standard Poodle',
  'Vizsla',
  'Weimaraner',
  'Whippet',
  'Yorkshire Terrier',
  'Mixed Breed',
  'Other',
]
